/* Para el formulario */
export const OBTENER_DATOS_FORMULARIO = 'OBTENER_DATOS_FORMULARIO';
export const ENVIAR_DATOS_FORMULARIO = 'ENVIAR_DATOS_FORMULARIO';
export const OBTENER_DATOS_FORMULARIO_ERROR = 'OBTENER_DATOS_FORMULARIO_ERROR';
export const ACTUALIZAR_DATOS_FORMULARIO = 'ACTUALIZAR_DATOS_FORMULARIO';
export const LIMPIAR_FORMULARIO = 'LIMPIAR_FORMULARIO';
export const TERMINAR_CARGANDO = 'TERMINAR_CARGANDO';
export const COLOCAR_GIF_CARGANDO = 'COLOCAR_GIF_CARGANDO';
export const OBTENER_DATOS_Y_ACTUALIZAR_FORMULARIO =
  'OBTENER_DATOS_Y_ACTUALIZAR_FORMULARIO';
export const OBTENER_RNC = 'OBTENER_RNC';
export const FORM_ESTADO = 'FORM_ESTADO';
export const OBTENER_PREGUNTAS_FORMULARIO = 'OBTENER_PREGUNTAS_FORMULARIO';
export const OBTENER_OPCIONES_PREGUNTAS_FORMULARIO =
  'OBTENER_OPCIONES_PREGUNTAS_FORMULARIO';

/* Para la autenticación y el manejo de sesión */
export const AUTENTICACION_ERROR = 'AUTENTICACION_ERROR';
export const CARGAR_USUARIO = 'CARGAR_USUARIO';
export const AUTENTICACION_EXITO = 'AUTENTICACION_EXITO';
export const AUTENTICACION_FALLO = 'AUTENTICACION_FALLO';
export const CERRAR_SESION = 'CERRAR_SESION';
export const LIMPIAR_ERRORES = 'LIMPIAR_ERRORES';

/* Para registro */
export const REGISTRO_EXITO = 'REGISTRO_EXITO';
export const REGISTRO_FALLO = 'REGISTRO_FALLO';

/* Para las alertas de todos los componentes */
export const ACTIVAR_ALERTA = 'ACTIVAR_ALERTA';
export const REMOVER_ALERTA = 'REMOVER_ALERTA';

/* Para la pantalla de admin */
export const OBTENER_SOLICITANTES = 'OBTENER_SOLICITANTES';
export const FILTRAR_SOLICITANTES = 'FILTRAR_SOLICITANTES';
export const LIMPIAR_SOLICITANTES = 'LIMPIAR_SOLICITANTES';
export const LIMPIAR_DATOS_SOLICITANTES = 'LIMPIAR_DATOS_SOLICITANTES';
export const COLOCAR_GIF_CARGANDOMODAL = 'COLOCAR_GIF_CARGANDOMODAL';
export const APLICAR_ESTADO_USR = 'APLICAR_ESTADO_USR';
export const LIMPIAR_ESTADO_USR = 'LIMPIAR_ESTADO_USR';
export const LIMPIAR_DATOS_MAESTROS = 'LIMPIAR_DATOS_MAESTROS';
export const DESBLOQUEAR_USUARIO = 'DESBLOQUEAR_USUARIO';
export const ALERTA_ADMIN = 'ALERTA_ADMIN';
export const BLOQUEAR_USUARIO = 'BLOQUEAR_USUARIO';
export const OBTENER_LISTA_CAMPOS_PENDIENTES_APRB =
  'OBTENER_LISTA_CAMPOS_PENDIENTES_APRB';
export const OBTENER_CANTIDAD_PENDIENTES = 'OBTENER_CANTIDAD_PENDIENTES';
export const OBTENER_SOLICITANTES_ESPECIFICOS =
  'OBTENER_SOLICITANTES_ESPECIFICOS';

/* Para la administración de archivos */
export const OBTENER_ARCHIVOS = 'OBTENER_ARCHIVOS';
export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const ELIMINAR_ARCHIVO = 'ELIMINAR_ARCHIVO';
export const COLOCAR_CARGANDO_ARCHIVOS = 'COLOCAR_CARGANDO_ARCHIVOS';
export const LIMPIAR_ARCHIVOS = 'LIMPIAR_ARCHIVOS';
export const QUITAR_CARGANDO_ARCHIVOS = 'QUITAR_CARGANDO_ARCHIVOS';
export const DESCARGAR_ARCHIVOS = 'DESCARGAR_ARCHIVOS';
